const assert=require('node:assert/strict');const{chromium}=require('playwright-core');const mode=process.argv[2],url=process.argv[3];
const outputs={back:'a phrase can turn backward without changing its held seeds',reverse:'reversing a drawing changes insertion order rather than playback settings',color:'keeping the struck note color preserves the surviving drawn order',braid:'a two-note braid alternates eight held seeds without starting playback'};
(async()=>{assert(outputs[mode]);const b=await chromium.launch({headless:true});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900}});assert.equal((await p.goto(url)).status(),200);const click=id=>p.locator('#'+id).click(),held=()=>p.evaluate(()=>__sunflower.heldInDrawnOrder()),snapshot=()=>p.evaluate(()=>({hold:__sunflower.holdEnabled(),erase:__sunflower.eraseEnabled(),root:__sunflower.root(),register:__sunflower.register(),reverse:__sunflower.reverseOrder(),bounce:__sunflower.bounceOrder(),sound:__sunflower.soundEnabled(),voices:__sunflower.lastVoices()}));const ids={back:'turn-back',reverse:'reverse-drawing',color:'keep-color',braid:'preset-two-note-braid'},id=ids[mode];if(mode!=='braid')assert(await p.isDisabled('#'+id));await click('preset-crossing-spirals');await click('order-drawn');const before=await snapshot(),base=await held();
if(mode==='back'){await click(id);assert.deepEqual(await held(),[220,0,34,68,102,136,170,204,55,110,165]);assert.equal(await p.textContent('#status'),'Moved the last held note to the beginning.');await click('turn-phrase');assert.deepEqual(await held(),base);}
if(mode==='reverse'){await click(id);assert.deepEqual(await held(),[220,165,110,55,204,170,136,102,68,34,0]);assert.equal(await p.textContent('#status'),'Reversed the drawn phrase.');assert.deepEqual(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()),await held());await click(id);assert.deepEqual(await held(),base);await click('order-radial');await click(id);assert.deepEqual(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()),[0,34,55,68,102,110,136,165,170,204,220]);}
if(mode==='color'){assert(await p.isDisabled('#'+id));await click('next-held');assert.equal(await p.evaluate(()=>__sunflower.struck()),0);assert(!(await p.isDisabled('#'+id)));await click(id);assert.deepEqual(await held(),[0,170,55,110,165,220]);assert.equal(await p.textContent('#status'),'Kept the held blooms in this note color.');assert(await p.isDisabled('#'+id));await click('preset-five-note-fan');await click('next-held');await click('next-held');assert.equal(await p.evaluate(()=>__sunflower.struck()),1);await click(id);assert.deepEqual(await held(),[1]);await click('preset-spiral-55');assert(await p.isDisabled('#'+id));}
if(mode==='braid'){await click(id);assert.deepEqual(await held(),[0,2,5,7,10,12,15,17]);assert.equal(await p.textContent('#status'),'Held Two-note braid. Play the blooms or brush in your own notes.');assert.deepEqual(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()),[0,2,5,7,10,12,15,17]);await click('reverse-order');assert.deepEqual(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()),[17,15,12,10,7,5,2,0]);await click('reverse-order');}
assert.deepEqual(await snapshot(),before);assert.equal(await p.evaluate(()=>__sunflower.bloomPlaybackRunning()),false);assert.equal(await p.evaluate(()=>__sunflower.traceRunning()||__sunflower.rippleRunning()),false);
await click('preset-crossing-spirals');if(mode==='color')await click('next-held');await click('tempo-slow');await click('play-blooms');assert(await p.isDisabled('#'+id));await p.waitForFunction(()=>!__sunflower.bloomPlaybackRunning());await click('clear-blooms');if(mode!=='braid')assert(await p.isDisabled('#'+id));assert((await p.locator('#'+id).boundingBox()).height>=44);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.close()}console.log(outputs[mode])}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
