const cases={
"rangesort":async(p,click,select,check)=>{await click('preset-two-note-braid');await select('edit-note','7');await select('edit-note-partner','15');const n=await p.evaluate(()=>__sunflower.undoDepth());await click('edit-note-range-sort-color');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),[0,2,5,10,15,7,12,17]);A.equal(await p.evaluate(()=>__sunflower.undoDepth()),n+1);await click('undo-drawing');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),[0,2,5,7,10,12,15,17]);A.equal(await p.evaluate(()=>__audio.starts),0);},
"rangecut":async(p,click,select,check)=>{await click('preset-two-note-braid');await select('edit-note','7');await select('edit-note-partner','15');await click('edit-note-range-keep-alternate');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),[0,2,5,7,12,17]);await click('undo-drawing');await click('edit-note-range-drop-alternate');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),[0,2,5,10,15,17]);await click('undo-drawing');A.equal(await p.evaluate(()=>__audio.starts),0);},
"rangeweave":async(p,click,select,check)=>{await click('preset-two-note-braid');await select('edit-note','5');await select('edit-note-partner','15');await click('edit-note-range-ends-in');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),[0,2,5,15,7,12,10,17]);await click('undo-drawing');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),[0,2,5,7,10,12,15,17]);A.equal(await p.evaluate(()=>__audio.starts),0);}
};
const messages={"rangesort": "a chosen section sorts by note color without moving its outside notes", "rangecut": "alternate cuts are counted from the beginning of the chosen section", "rangeweave": "chosen section ends weave inward while every outside seed stays put"};
const A=require('node:assert/strict'),{chromium}=require('playwright-core');const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={buffers:[],starts:0,stops:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(ch,n,r){const a=new Float32Array(n);const b={length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)};__audio.buffers.push(b);return b}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){__audio.stops++},loop:false}}}window.AudioContext=C;window.webkitAudioContext=C};
(async()=>{A.ok(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});for(const width of[390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(String(e)));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(100);const reveal=async l=>{const ds=await l.evaluate(e=>{let a=[];for(let x=e.parentElement;x;x=x.parentElement)if(x.tagName==='DETAILS'&&!x.open)a.unshift(x.id);return a});for(const d of ds){const s=p.locator('#'+d+'>summary');await s.scrollIntoViewIfNeeded();await s.click()}};const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A.ok(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}));await l.click();await p.waitForTimeout(60)};const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(60)};const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(60)};await cases[mode](p,click,select,check);A.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));A.deepEqual(errors,[]);await p.screenshot({path:`/tmp/pm-${mode}-${width}.png`,fullPage:true});await p.close()}await b.close();console.log(messages[mode])})().catch(e=>{console.error(e);process.exit(1)});
