const A=require('node:assert/strict'),{chromium}=require('playwright-core');
const mode=process.argv[2],url=process.argv[3];
const audio=()=>{window.__audio={starts:0};class C{constructor(){this.sampleRate=48000;this.destination={};this.currentTime=0}resume(){return Promise.resolve()}createBuffer(c,n,r){const a=new Float32Array(n);return{length:n,duration:n/r,sampleRate:r,getChannelData:()=>a,copyToChannel:s=>a.set(s)}}createBufferSource(){return{connect(){},disconnect(){},start(){__audio.starts++},stop(){}}}}window.AudioContext=C;window.webkitAudioContext=C};
const cases={
"rangesize":async(p,click,select,check)=>{await click('preset-two-note-braid');await select('edit-note','7');await select('edit-note-partner','15');await click('edit-note-reverse-range');const old=await p.evaluate(()=>__sunflower.heldInDrawnOrder()),n=await p.evaluate(()=>__sunflower.undoDepth());await click('edit-note-range-outward');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),[0,2,5,7,10,12,15,17]);A.equal(await p.evaluate(()=>__sunflower.undoDepth()),n+1);A(await p.locator('#edit-note-range-outward').isDisabled());await click('undo-drawing');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),old);await click('edit-note-range-outward');await click('edit-note-range-inward');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),[0,2,5,15,12,10,7,17]);A.equal(await p.evaluate(()=>__audio.starts),0);},
"rangechanges":async(p,click,select,check)=>{await click('preset-two-note-braid');await select('edit-note','7');await select('edit-note-partner','15');await click('edit-note-range-sort-color');await select('edit-note','5');await select('edit-note-partner','12');const old=await p.evaluate(()=>__sunflower.heldInDrawnOrder()),n=await p.evaluate(()=>__sunflower.undoDepth());await click('edit-note-range-changes');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),[0,2,5,7,17]);A.equal(await p.evaluate(()=>__sunflower.undoDepth()),n+1);await click('undo-drawing');A.deepEqual(await p.evaluate(()=>__sunflower.heldInDrawnOrder()),old);A.equal(await p.evaluate(()=>__audio.starts),0);}
};
const messages={"rangesize": "a chosen section sorts by seed radius without changing its neighbors", "rangechanges": "only consecutive color repeats inside the chosen passage are removed"};

(async()=>{A(cases[mode]);const b=await chromium.launch({args:['--no-sandbox']});try{for(const width of [390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await p.addInitScript(audio);const errors=[];p.on('pageerror',e=>errors.push(e.message));A.equal((await p.goto(url)).status(),200);await p.waitForTimeout(120);
const reveal=async l=>{const ids=await l.evaluate(e=>{let a=[];for(let n=e.parentElement;n;n=n.parentElement)if(n.tagName==='DETAILS'&&!n.open)a.unshift(n.id);return a});for(const id of ids){A(id);await p.locator('#'+id+'>summary').scrollIntoViewIfNeeded();await p.locator('#'+id+'>summary').click()}};
const click=async id=>{const l=p.locator('#'+id);await reveal(l);await l.scrollIntoViewIfNeeded();A(await l.isEnabled(),id+' enabled');A(await l.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}),id+' hit');await l.click();await p.waitForTimeout(70)};
const select=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.selectOption(v);await p.waitForTimeout(70)};
const check=async(id,v)=>{const l=p.locator('#'+id);await reveal(l);await l.setChecked(v);await p.waitForTimeout(70)};
await cases[mode](p,click,select,check);A.deepEqual(errors,[]);A(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/planner-oct9-${mode}-${width}.png`,fullPage:true});await p.close();}console.log(messages[mode]);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
