const {chromium}=require('playwright-core');
const url=process.argv[2]||'http://localhost:3000/';
const tolerance=70;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitUntil(fn,timeout=4000){const end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await wait(10)}throw Error('timeout')}
(async()=>{const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>{if(r.url().startsWith(url))errors.push(r.url())});await p.goto(url);
if(await p.evaluate(()=>__sunflower.tempo())!=='flow'||await p.evaluate(()=>__sunflower.stepDuration())!==80||await p.locator('#tempo-flow').getAttribute('aria-pressed')!=='true'||await p.locator('#tempos').evaluate(el=>el.previousElementSibling.id)!=='roots'||await p.locator('#roots').evaluate(el=>el.previousElementSibling.id)!=='registers')throw Error('flow tempo');
for(const [name,duration] of [['slow',140],['flow',80],['quick',45]]){await p.locator(`#tempo-${name}`).click();if(await p.evaluate(()=>__sunflower.tempo())!==name||await p.evaluate(()=>__sunflower.stepDuration())!==duration)throw Error(`${name} tempo`)}
const registerButtons=p.locator('#registers button');if(await p.evaluate(()=>__sunflower.register())!=='middle'||Math.abs(await p.evaluate(()=>__sunflower.frequencyFor(0))-261.63)>1e-6||await p.locator('#registers button[aria-pressed="true"]').count()!==1)throw Error('middle register');
await p.locator('#register-low').click();if(await p.evaluate(()=>__sunflower.register())!=='low'||Math.abs(await p.evaluate(()=>__sunflower.frequencyFor(0))-130.815)>1e-6||await p.evaluate(()=>__sunflower.soundEnabled()))throw Error('low register');await p.locator('#register-high').click();if(await p.evaluate(()=>__sunflower.register())!=='high'||Math.abs(await p.evaluate(()=>__sunflower.frequencyFor(0))-523.26)>1e-6)throw Error('high register');await p.locator('#register-middle').click();if(await p.evaluate(()=>__sunflower.register())!=='middle'||Math.abs(await p.evaluate(()=>__sunflower.frequencyFor(0))-261.63)>1e-6)throw Error('middle return');
const direction=p.locator('#trace-direction');if(await p.locator('#trace-34').textContent()!=='Trace 34'||await p.locator('#trace-55').textContent()!=='Trace 55'||await direction.textContent()!=='Trace inward'||await direction.getAttribute('aria-pressed')!=='false')throw Error('copy');if(JSON.stringify(await p.evaluate(()=>({r:__sunflower.traceRunning(),s:__sunflower.traceStride(),k:__sunflower.traceStep(),inward:__sunflower.traceInward(),a:__sunflower.traceIndexes(7,34),ia:__sunflower.traceIndexes(7,34,true)})))!==JSON.stringify({r:false,s:0,k:-1,inward:false,a:[7,41,75,109,143,177,211,12,46,80,114,148,182,216,17,51],ia:[7,206,172,138,104,70,36,2,201,167,133,99,65,31,230,196]}))throw Error('idle hooks');
await direction.click();if(await direction.textContent()!=='Tracing inward'||await direction.getAttribute('aria-pressed')!=='true'||!await p.evaluate(()=>__sunflower.traceInward()))throw Error('inward toggle');const pt=await p.evaluate(()=>({p:__sunflower.points()[7],b:document.querySelector('canvas').getBoundingClientRect().toJSON()}));await p.mouse.click(pt.b.x+pt.p.x,pt.b.y+pt.p.y);if(await p.evaluate(()=>__sunflower.struck())!==7)throw Error('strike');
await p.locator('#register-high').click();if(await p.evaluate(()=>__sunflower.register())!=='high'||await p.evaluate(()=>__sunflower.soundEnabled()))throw Error('register trace');await p.locator('#tempo-flow').click();const flowStart=Date.now();await p.locator('#trace-34').click();if(!await p.evaluate(()=>__sunflower.traceRunning()))throw Error('trace start');await wait(20);if(await p.evaluate(()=>__sunflower.traceStep())!==0)throw Error('first step');await waitUntil(()=>p.evaluate(()=>!__sunflower.traceRunning()));const flowElapsed=Date.now()-flowStart;if(Math.abs(flowElapsed-1280)>tolerance)throw Error(`flow timing ${flowElapsed}`);if(await p.evaluate(()=>__sunflower.traceStep())!==-1)throw Error('finish');
await p.locator('#tempo-quick').click();const quickStart=Date.now();await p.locator('#trace-55').click();await wait(70);await p.locator('#tempo-slow').click();if(!await p.evaluate(()=>__sunflower.traceRunning()))throw Error('captured running');await waitUntil(()=>p.evaluate(()=>!__sunflower.traceRunning()));const quickElapsed=Date.now()-quickStart;if(Math.abs(quickElapsed-720)>tolerance)throw Error(`captured timing ${quickElapsed}`);if(await p.evaluate(()=>__sunflower.tempo())!=='slow')throw Error('tempo persistence');
await direction.click();if(await direction.textContent()!=='Trace inward'||await direction.getAttribute('aria-pressed')!=='false'||await p.evaluate(()=>__sunflower.traceInward()))throw Error('outward toggle');if(JSON.stringify(await p.evaluate(()=>__sunflower.traceIndexes(7,34)))!==JSON.stringify([7,41,75,109,143,177,211,12,46,80,114,148,182,216,17,51]))throw Error('outward indexes');
const p100=await p.evaluate(()=>({p:__sunflower.points()[100],b:document.querySelector('canvas').getBoundingClientRect().toJSON()}));await p.locator('#tempo-flow').click();await p.locator('#trace-55').click();await wait(80);await p.mouse.click(p100.b.x+p100.p.x,p100.b.y+p100.p.y);if(await p.evaluate(()=>__sunflower.struck())!==100||await p.evaluate(()=>__sunflower.traceRunning()))throw Error('cancel');await p.locator('#ripple').click();await p.locator('#trace-34').click();if(await p.evaluate(()=>__sunflower.rippleRunning())||await p.evaluate(()=>__sunflower.traceRunning())!==true)throw Error('ripple cancel');await wait(1300);await p.locator('#sound-toggle').click();await p.locator('#trace-55').click();await wait(1300);if(!await p.evaluate(()=>__sunflower.soundEnabled())||await p.evaluate(()=>document.documentElement.scrollWidth>390))throw Error('sound or overflow');if(errors.length)throw Error(errors.join(';'));console.log('34-step and 55-step Fibonacci seed spirals traced from touch')}catch(e){console.error(e);process.exitCode=1}finally{await b.close()}})();