const {chromium}=require('playwright-core');
const url=process.argv[2]||'http://localhost:3000/';
const tolerance=70;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitUntil(fn,timeout=4000){const end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await wait(10)}throw Error('timeout')}
(async()=>{const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>{if(r.url().startsWith(url))errors.push(r.url())});await p.goto(url);
if(await p.evaluate(()=>__sunflower.tempo())!=='flow'||await p.evaluate(()=>__sunflower.stepDuration())!==80||await p.locator('#tempo-flow').getAttribute('aria-pressed')!=='true')throw Error('flow tempo');if(await p.locator('#tempos').evaluate(el=>el.previousElementSibling.id)!=='registers'||await p.evaluate(()=>document.documentElement.scrollWidth>390))throw Error('phone fit');for(const button of await p.locator('#tempos button').all()){if((await button.boundingBox()).height<44)throw Error('tempo target')}
const registerButtons=p.locator('#registers button');if(await p.evaluate(()=>__sunflower.register())!=='middle'||Math.abs(await p.evaluate(()=>__sunflower.frequencyFor(0))-261.63)>1e-6||await p.locator('#registers button[aria-pressed="true"]').count()!==1)throw Error('middle register');await p.locator('#register-low').click();if(await p.evaluate(()=>__sunflower.register())!=='low'||Math.abs(await p.evaluate(()=>__sunflower.frequencyFor(0))-130.815)>1e-6||await p.evaluate(()=>__sunflower.soundEnabled()))throw Error('low register');await p.locator('#register-high').click();if(await p.evaluate(()=>__sunflower.register())!=='high'||Math.abs(await p.evaluate(()=>__sunflower.frequencyFor(0))-523.26)>1e-6)throw Error('high register');await p.locator('#register-middle').click();
const flowStart=Date.now();await p.locator('#ripple').click();await p.locator('#register-low').click();if(!await p.evaluate(()=>__sunflower.rippleRunning())||await p.evaluate(()=>__sunflower.register())!=='low'||await p.evaluate(()=>__sunflower.soundEnabled())||!await p.locator('#ripple').isDisabled()||await p.locator('#ripple').textContent()!=='Rippling…')throw Error('running state');await wait(20);if(await p.evaluate(()=>__sunflower.rippleBand())!==0)throw Error('first band');await waitUntil(()=>p.evaluate(()=>!__sunflower.rippleRunning()));const flowElapsed=Date.now()-flowStart;if(Math.abs(flowElapsed-960)>tolerance)throw Error(`flow timing ${flowElapsed}`);if(await p.evaluate(()=>__sunflower.rippleBand())!==-1||await p.locator('#status').textContent()!=='Sound is off. The garden still glows.')throw Error('completion');
await p.locator('#tempo-quick').click();const quickStart=Date.now();await p.locator('#ripple').click();await wait(70);await p.locator('#tempo-slow').click();if(!await p.evaluate(()=>__sunflower.rippleRunning()))throw Error('captured running');await waitUntil(()=>p.evaluate(()=>!__sunflower.rippleRunning()));const quickElapsed=Date.now()-quickStart;if(Math.abs(quickElapsed-540)>tolerance)throw Error(`captured timing ${quickElapsed}`);
await p.locator('#ripple').click();await wait(120);const v=await p.evaluate(()=>({point:__sunflower.points()[100],box:document.querySelector('canvas').getBoundingClientRect().toJSON()}));await p.mouse.click(v.box.x+v.point.x,v.box.y+v.point.y);if(await p.evaluate(()=>__sunflower.rippleRunning())||await p.evaluate(()=>__sunflower.struck())!==100)throw Error('yield');await p.locator('#sound-toggle').click();await p.locator('#tempo-quick').click();await p.locator('#ripple').click();await waitUntil(()=>p.evaluate(()=>!__sunflower.rippleRunning()));if(!await p.evaluate(()=>__sunflower.soundEnabled())||await p.evaluate(()=>document.documentElement.scrollWidth>390))throw Error('sound or overflow');if(errors.length)throw Error(errors.join(';'));console.log('twelve sunflower bands ripple outward and yield to touch')}catch(e){console.error(e);process.exitCode=1}finally{await b.close()}})();