const {chromium}=require('playwright-core');
const url=process.argv[2]||'http://localhost:3000/';
const tolerance=70;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitUntil(fn,timeout=5000){const end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await wait(10)}throw Error('timeout')}
(async()=>{const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>{if(r.url().startsWith(url))errors.push(r.url())});await p.goto(url);
if(await p.title()!=='Sunflower Keys')throw Error('title');
const initial=await p.evaluate(()=>({n:__sunflower.seedCount(),a:__sunflower.goldenAngle(),pts:__sunflower.points(),overflow:document.documentElement.scrollWidth>390,tempo:__sunflower.tempo(),duration:__sunflower.stepDuration(),canvas:document.querySelector('canvas').getBoundingClientRect().width}));
if(initial.n!==233||Math.abs(initial.a-2.399963229728653)>1e-12||initial.overflow||initial.canvas!==390||!initial.pts.every(q=>Number.isFinite(q.x)&&Number.isFinite(q.y)))throw Error('geometry');
if(await p.evaluate(()=>__sunflower.playOrder())!=='radial'||await p.locator('#order-radial').getAttribute('aria-pressed')!=='true'||await p.locator('#order-drawn').getAttribute('aria-pressed')!=='false')throw Error('initial playback order');
for(const [name,duration] of [['slow',140],['flow',80],['quick',45]]){await p.locator(`#tempo-${name}`).click();if(await p.evaluate(()=>__sunflower.tempo())!==name||await p.evaluate(()=>__sunflower.stepDuration())!==duration||await p.locator(`#tempo-${name}`).getAttribute('aria-pressed')!=='true'||await p.locator('#tempos button[aria-pressed="true"]').count()!==1)throw Error(`${name} tempo`)}
for(const button of await p.locator('#tempos button').all()){if((await button.boundingBox()).height<44)throw Error('tempo target')}
for(const button of await p.locator('#play-orders button').all()){if((await button.boundingBox()).height<44)throw Error('order target')}
await p.locator('#sound-toggle').click();if(await p.locator('#status').textContent()!=='Sound is on. Tap or drag across the seeds.')throw Error('sound');
const box=await p.locator('canvas').boundingBox(),points=await p.evaluate(()=>__sunflower.points());
const clickSeed=async i=>p.mouse.click(box.x+points[i].x,box.y+points[i].y);
await p.locator('#hold-blooms').click();for(const i of [100,7,40])await clickSeed(i);
if(JSON.stringify(await p.evaluate(()=>__sunflower.heldInDrawnOrder()))!=='[100,7,40]')throw Error('drawn order');
if(JSON.stringify(await p.evaluate(()=>__sunflower.held()))!=='[7,40,100]')throw Error('radial held order');
if(JSON.stringify(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()))!=='[7,40,100]')throw Error('radial playback order');
await clickSeed(7);await clickSeed(100);if(JSON.stringify(await p.evaluate(()=>__sunflower.heldInDrawnOrder()))!=='[100,7,40]')throw Error('duplicate stability');
await p.locator('#order-drawn').click();if(await p.evaluate(()=>__sunflower.playOrder())!=='drawn'||JSON.stringify(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()))!=='[100,7,40]')throw Error('drawn playback order');
await p.locator('#tempo-slow').click();await p.locator('#play-blooms').click();if(await p.locator('#status').textContent()!=='Playing 3 held blooms in the order you drew them.')throw Error('drawn status');await waitUntil(()=>p.evaluate(()=>!__sunflower.bloomPlaybackRunning()));
await p.locator('#play-blooms').click();if(await p.locator('#status').textContent()!=='Playing 3 held blooms in the order you drew them.')throw Error('drawn replay');await waitUntil(()=>p.evaluate(()=>!__sunflower.bloomPlaybackRunning()));
await p.locator('#clear-blooms').click();for(const i of [20,40,60])await clickSeed(i);await p.locator('#tempo-slow').click();const slowStart=Date.now();await p.locator('#play-blooms').click();if(!await p.evaluate(()=>__sunflower.bloomPlaybackRunning()))throw Error('slow start');await waitUntil(()=>p.evaluate(()=>!__sunflower.bloomPlaybackRunning()));const slowElapsed=Date.now()-slowStart;if(Math.abs(slowElapsed-420)>tolerance)throw Error(`slow timing ${slowElapsed}`);
await p.locator('#clear-blooms').click();for(const i of [20,40,60])await clickSeed(i);await p.locator('#tempo-quick').click();const quickStart=Date.now();await p.locator('#play-blooms').click();await wait(70);await p.locator('#tempo-slow').click();if(!await p.evaluate(()=>__sunflower.bloomPlaybackRunning()))throw Error('captured running');await waitUntil(()=>p.evaluate(()=>!__sunflower.bloomPlaybackRunning()));const quickElapsed=Date.now()-quickStart;if(Math.abs(quickElapsed-135)>tolerance)throw Error(`captured timing ${quickElapsed}`);if(await p.evaluate(()=>__sunflower.tempo())!=='slow'||!await p.evaluate(()=>__sunflower.soundEnabled()))throw Error('tempo or sound persistence');
await p.locator('#clear-blooms').click();if(JSON.stringify(await p.evaluate(()=>__sunflower.heldInDrawnOrder()))!=='[]'||JSON.stringify(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()))!=='[]')throw Error('clear');
for(let i=0;i<25;i++)await clickSeed(i);if(JSON.stringify(await p.evaluate(()=>__sunflower.heldInDrawnOrder()))!==JSON.stringify(Array.from({length:25},(_,i)=>i)))throw Error('25 drawn seeds');
if(JSON.stringify(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()))!==JSON.stringify(Array.from({length:24},(_,i)=>i)))throw Error('drawn cap');
if(await p.locator('#status').textContent()!=='Sound is on. Tap or drag across the seeds.')throw Error('ordinary status');
await p.locator('#tempo-slow').click();await p.locator('#play-blooms').click();if(await p.locator('#status').textContent()!=='Playing the first 24 blooms in the order you drew them.')throw Error('drawn capped status');await wait(30);await p.locator('#order-radial').click();if(!await p.evaluate(()=>__sunflower.bloomPlaybackRunning())||JSON.stringify(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()))!==JSON.stringify(Array.from({length:24},(_,i)=>i)))throw Error('mid-run selection capture');await waitUntil(()=>p.evaluate(()=>!__sunflower.bloomPlaybackRunning()));if(await p.evaluate(()=>__sunflower.playOrder())!=='radial'||JSON.stringify(await p.evaluate(()=>__sunflower.bloomPlaybackIndexes()))!==JSON.stringify(Array.from({length:24},(_,i)=>i)))throw Error('radial cap');
if(errors.length)throw Error(errors.join(';'));await b.close();console.log('233 golden-angle seeds glow and sing under pointer gestures')}catch(e){console.error(e);process.exitCode=1}finally{await b.close()}})();
